# Generated by Django 4.0.2 on 2023-10-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classes', '0001_initial'),
        ('StudentsGroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsPerClasses',
            fields=[
                ('groupsperclassesid', models.AutoField(db_column='GroupsPerClassesId', primary_key=True, serialize=False)),
                ('classesid', models.ForeignKey(blank=True, db_column='ClassesId', null=True, on_delete=django.db.models.deletion.CASCADE, to='Classes.classes')),
                ('studentsgroupsid', models.ForeignKey(blank=True, db_column='StudentsGroupsId', null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentsGroups.studentsgroups')),
            ],
            options={
                'db_table': 'groupsperclasses',
            },
        ),
    ]
