# Generated by Django 3.2.23 on 2023-11-21 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsCreate', '0001_initial'),
        ('GroupsPerClasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsperclasses',
            name='groupscreatedid',
            field=models.ForeignKey(blank=True, db_column='GroupsCreatedId', null=True, on_delete=django.db.models.deletion.CASCADE, to='GroupsCreate.groupscreate'),
        ),
    ]
