# Generated by Django 4.0.2 on 2022-05-02 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCreator',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('teacherId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('order', models.IntegerField(primary_key=True, serialize=False)),
                ('imgUrl', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('pageNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('contentsList', models.ManyToManyField(related_name='pages', related_query_name='pages', to='BookCreator.Content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', related_query_name='contents', to='BookCreator.page'),
        ),
    ]
