version: '3.8'

services:
  frontend:
    container_name: funread_frontend
    image: funreaducr/frontend:a3b35656-eea2-4d87-bb4d-c17933456931
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app  
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  backend:
    container_name: funread_backend
    image: funreaducr/backend:a3b35656-eea2-4d87-bb4d-c17933456931
    build:
      context: ./funread_backend
      dockerfile: Dockerfile
    volumes:
      - ./funread_backend:/app
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DEBUG=True
      - SETTINGS_DATABASE_HOST=mysql
      - SETTINGS_DATABASE_NAME=FUNREAD
      - SETTINGS_DATABASE_USER=user
      - SETTINGS_DATABASE_PASSWORD=password
    restart: always

  mysql:
    platform: linux/x86_64
    container_name: funread_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FUNREAD
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql_data: