version: '3.8'

services:
  frontend:
    container_name: funread_frontend
    image: funreaducr/frontend:main
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  backend:
    container_name: funread_backend
    image: funreaducr/backend:main
    build:
      context: ./funread_backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - SETTINGS_DATABASE_HOST=mysql
      - SETTINGS_DATABASE_NAME=FUNREAD
      - SETTINGS_DATABASE_USER=user
      - SETTINGS_DATABASE_PASSWORD=password
    restart: always

  mysql:
    container_name: funread_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FUNREAD
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql_data: