# Generated by Django 4.0.2 on 2022-11-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tags', '0002_alter_tags_description'),
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsPerBook',
            fields=[
                ('tagsperbookid', models.AutoField(primary_key=True, serialize=False)),
                ('bookid', models.ForeignKey(db_column='bookid', on_delete=django.db.models.deletion.CASCADE, related_name='bookiddb', to='Books.book')),
                ('tagsid', models.ForeignKey(db_column='tagsid', on_delete=django.db.models.deletion.CASCADE, related_name='tagsiddb', to='Tags.tags')),
            ],
        ),
    ]
