# Generated by Django 4.0.2 on 2024-11-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('bookcategoryid', models.AutoField(db_column='BookCategoryID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='CategoryName', max_length=100)),
            ],
            options={
                'db_table': 'bookcategory',
            },
        ),
        migrations.CreateModel(
            name='BookDilemma',
            fields=[
                ('bookdilemmaid', models.AutoField(db_column='BookDilemmaID', primary_key=True, serialize=False)),
                ('dilemma', models.CharField(db_column='Dilemma', max_length=500)),
            ],
            options={
                'db_table': 'bookdilemma',
            },
        ),
        migrations.CreateModel(
            name='DilemmaPerBook',
            fields=[
                ('dilemmaperbookid', models.AutoField(db_column='DilemmaPerBookID', primary_key=True, serialize=False)),
                ('bookdilemmaid', models.ForeignKey(db_column='BookDilemmaID', on_delete=django.db.models.deletion.CASCADE, related_name='DilemmaPerBook_book_dilemma_dilemma', to='BooksDilemma.bookdilemma')),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, related_name='DilemmaPerBook_book_id_book', to='Books.book')),
            ],
            options={
                'db_table': 'dilemmaperbook',
            },
        ),
        migrations.CreateModel(
            name='BookDimension',
            fields=[
                ('bookdimensionid', models.AutoField(db_column='BookDimensionID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='DimensionName', max_length=150)),
                ('bookcategoryid', models.ForeignKey(db_column='BookCategoryID', on_delete=django.db.models.deletion.CASCADE, related_name='DilemmaPerBook_book_category_dimension', to='BooksDilemma.bookcategory')),
            ],
            options={
                'db_table': 'bookdimension',
            },
        ),
        migrations.AddField(
            model_name='bookdilemma',
            name='bookdimensionid',
            field=models.ForeignKey(db_column='BookDimensionID', on_delete=django.db.models.deletion.CASCADE, related_name='DilemmaPerBook_book_dimension_dilemma', to='BooksDilemma.bookdimension'),
        ),
    ]
