# Generated by Django 4.0.2 on 2025-08-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksDilemma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bookdilemma',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bookdimension',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=500, null=True),
        ),
    ]
