# Generated by Django 4.0.2 on 2024-11-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('extension', models.CharField(max_length=10)),
                ('file', models.FileField(blank='', default='', upload_to='media/')),
                ('type', models.IntegerField()),
                ('galleryType', models.IntegerField(blank=True, db_column='galleryType', null=True)),
            ],
            options={
                'db_table': 'media',
            },
        ),
    ]
