# Generated by Django 4.0.2 on 2023-09-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
