# Generated by Django 4.0.2 on 2025-11-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_media_user_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='isfunreadMedia',
            field=models.BooleanField(default=False),
        ),
    ]
