# Generated by Django 4.0.2 on 2023-09-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='url',
            new_name='route',
        ),
    ]
