# Generated by Django 4.2.4 on 2023-11-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_alter_media_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank='', default='', upload_to='media/'),
        ),
    ]
