# Generated by Django 4.2.4 on 2023-11-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0003_remove_media_image_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
