# Generated by Django 4.0.2 on 2023-09-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0003_rename_url_media_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='route',
        ),
    ]
