# Generated by Django 4.0.2 on 2023-10-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('emailid', models.AutoField(db_column='emailId', primary_key=True, serialize=False)),
                ('emailto', models.CharField(db_column='emailTo', max_length=200)),
                ('emailfrom', models.CharField(db_column='emailFrom', max_length=200)),
                ('emailsubject', models.CharField(db_column='emailSubject', max_length=50)),
                ('bodymessage', models.TextField(db_column='bodyMessage', max_length=500)),
            ],
            options={
                'db_table': 'mail',
            },
        ),
        migrations.CreateModel(
            name='MailControl',
            fields=[
                ('mailcontrolid', models.AutoField(db_column='mailControlId', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='date')),
                ('category', models.IntegerField(db_column='category')),
                ('status', models.CharField(max_length=5)),
                ('emailfrom', models.ForeignKey(db_column='emailFrom', on_delete=django.db.models.deletion.CASCADE, to='Users.user', to_field='email')),
                ('idcontrol', models.ForeignKey(blank=True, db_column='idControl', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mailer.mail')),
            ],
            options={
                'db_table': 'mailcontrol',
            },
        ),
    ]
