# Generated by Django 4.0.2 on 2022-10-20 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('emailId', models.AutoField(primary_key=True, serialize=False)),
                ('emailTo', models.CharField(max_length=200)),
                ('emailFrom', models.CharField(max_length=200)),
                ('emailSubject', models.CharField(blank=True, max_length=50, null=True)),
                ('bodyMessage', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MailControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='date')),
                ('category', models.IntegerField(db_column='category')),
                ('status', models.CharField(max_length=5)),
                ('idControl', models.ForeignKey(db_column='idControl', on_delete=django.db.models.deletion.CASCADE, related_name='idControl', to='Mailer.mail')),
            ],
        ),
    ]
