# Generated by Django 4.0.2 on 2023-11-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mailer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='bodymessage',
            new_name='bodyMessage',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='emailfrom',
            new_name='emailFrom',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='emailsubject',
            new_name='emailSubject',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='emailto',
            new_name='emailTo',
        ),
        migrations.RenameField(
            model_name='mailcontrol',
            old_name='emailfrom',
            new_name='emailFrom',
        ),
    ]
