# Generated by Django 4.0.2 on 2022-10-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='bodyMessage',
            field=models.TextField(max_length=500),
        ),
    ]
