# Generated by Django 4.0.2 on 2024-09-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailer', '0002_rename_bodymessage_mail_bodymessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='emailFrom',
            field=models.CharField(db_column='emailFrom', max_length=254),
        ),
        migrations.AlterField(
            model_name='mail',
            name='emailSubject',
            field=models.CharField(db_column='emailSubject', max_length=100),
        ),
        migrations.AlterField(
            model_name='mail',
            name='emailTo',
            field=models.CharField(db_column='emailTo', max_length=254),
        ),
    ]
