# Generated by Django 4.0.2 on 2023-10-06 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classes', '0001_initial'),
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joins',
            fields=[
                ('joinid', models.AutoField(db_column='joinId', primary_key=True, serialize=False)),
                ('code', models.TextField(db_column='code')),
                ('password', models.TextField(db_column='password', max_length=256)),
                ('bookid', models.ForeignKey(db_column='bookId', null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('classesId', models.ForeignKey(db_column='classesId', null=True, on_delete=django.db.models.deletion.CASCADE, to='Classes.classes')),
            ],
            options={
                'db_table': 'invitations',
            },
        ),
    ]
