# Generated by Django 4.0.2 on 2023-09-28 20:05

import Joins.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
        ('Classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joins',
            fields=[
                ('joinid', Joins.models.CustomAutoField(db_column='joinId', default=123456, editable=False, primary_key=True, serialize=False)),
                ('password', models.TextField(db_column='password', max_length=7)),
                ('bookid', models.ForeignKey(db_column='bookId', null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('classesId', models.ForeignKey(db_column='classesId', null=True, on_delete=django.db.models.deletion.CASCADE, to='Classes.classes')),
            ],
            options={
                'db_table': 'joins',
            },
        ),
    ]
