# Generated by Django 4.0.2 on 2023-10-02 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Joins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joins',
            name='code',
            field=models.TextField(db_column='code', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joins',
            name='joinid',
            field=models.AutoField(db_column='joinId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='joins',
            name='password',
            field=models.TextField(db_column='password', max_length=256),
        ),
    ]
