# Generated by Django 4.0.2 on 2023-10-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Joins', '0002_joins_code_alter_joins_joinid_alter_joins_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='joins',
            table='invitations',
        ),
    ]
