# Generated by Django 4.0.2 on 2023-10-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='Email', max_length=200, unique=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=200, null=True)),
                ('password', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=256, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('actived', models.IntegerField(blank=True, db_column='Actived', null=True)),
                ('username', models.CharField(db_column='UserName', max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
