# Generated by Django 4.0.2 on 2024-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, db_column='Level', max_length=50, null=True),
        ),
    ]
