# Generated by Django 4.0.2 on 2023-09-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0004_delete_userroles'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='Roles.Roles'),
        ),
    ]
