# Generated by Django 4.0.2 on 2024-11-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, db_column='Level', null=True),
        ),
    ]
