# Generated by Django 4.0.2 on 2024-09-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_column='Email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=128, null=True),
        ),
    ]
