# Generated by Django 4.0.2 on 2023-09-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
