# Generated by Django 4.0.2 on 2024-10-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=200)),
                ('level', models.IntegerField(db_column='Level')),
            ],
            options={
                'db_table': 'User_Levels',
            },
        ),
    ]
