# Generated by Django 4.0.2 on 2024-10-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamUser', '0001_initial'),
        ('UserPointsLog', '0001_initial'),
        ('User_Levels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserLevels',
        ),
    ]
