# Generated by Django 4.1.3 on 2022-11-12 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('instituteId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteMembers',
            fields=[
                ('instituteMembersId', models.AutoField(primary_key=True, serialize=False)),
                ('instituteId', models.ForeignKey(db_column='instituteId', on_delete=django.db.models.deletion.CASCADE, related_name='instituteId1', to='Institute.institute')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='userId1', to='Users.user')),
            ],
        ),
    ]
