# Generated by Django 4.1.3 on 2022-11-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
