//agregar todas las peticiones en este index, para que no se necesite indicar explicitamente cual peticion se necesita

export * from "./axiosInstances"
export * from "./users"
export * from "./invitations"
export * from "./books"
export * from "./group"
export * from "./media"
export * from "./studentGroups"
export * from "./translate"
export * from "./roles"
export * from "./userroles"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"
// export * from "./"


