# Generated by Django 4.0.2 on 2025-05-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AvatarCreator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avatarcreator',
            table='avatarcreator',
        ),
    ]
