# Generated by Django 4.0.2 on 2025-09-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvatarCreator', '0002_alter_avatarcreator_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarcreator',
            name='hair',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatarcreator',
            name='head',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatarcreator',
            name='pants',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatarcreator',
            name='shirt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avatarcreator',
            name='hair_style',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avatarcreator',
            name='skin_color',
            field=models.IntegerField(),
        ),
    ]
