# Generated by Django 4.0.2 on 2024-11-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('pageid', models.AutoField(db_column='PageId', primary_key=True, serialize=False)),
                ('type', models.IntegerField(db_column='Type')),
                ('template', models.IntegerField(db_column='Template')),
                ('elementorder', models.IntegerField(db_column='ElementOrder')),
                ('gridDirection', models.TextField(blank=True, db_column='GridDirection', null=True)),
                ('gridNumRows', models.IntegerField(blank=True, db_column='GridNumRows', null=True)),
                ('actived', models.IntegerField(blank=True, db_column='Actived', null=True)),
                ('bookid', models.ForeignKey(blank=True, db_column='BookId', null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
            options={
                'db_table': 'pages',
            },
        ),
    ]
