# Generated by Django 4.1.1 on 2022-10-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('pageid', models.AutoField(db_column='pageid', primary_key=True, serialize=False)),
                ('elementorder', models.IntegerField(db_column='elementorder')),
                ('type', models.IntegerField(db_column='type')),
                ('template', models.IntegerField(db_column='template')),
                ('book', models.ForeignKey(db_column='book', on_delete=django.db.models.deletion.CASCADE, related_name='book', to='Books.book')),
            ],
        ),
    ]
