# Generated by Django 4.0.2 on 2023-10-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='gridid',
            field=models.IntegerField(db_column='GridId', default='1'),
            preserve_default=False,
        ),
    ]
