# Generated by Django 4.0.2 on 2023-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='gridDirection',
            field=models.TextField(blank=True, db_column='GridDirection', null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='gridNumRows',
            field=models.IntegerField(blank=True, db_column='GridNumRows', null=True),
        ),
    ]
