# Generated by Django 4.0.2 on 2023-11-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_pages_griddirection_pages_gridnumrows'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='actived',
            field=models.IntegerField(blank=True, db_column='Actived', null=True),
        ),
    ]
