# Generated by Django 4.0.2 on 2023-10-06 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pages', '0001_initial'),
        ('Tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsPerPage',
            fields=[
                ('tagsperpageid', models.AutoField(db_column='TagsPerPageId', primary_key=True, serialize=False)),
                ('pageid', models.ForeignKey(blank=True, db_column='PageID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Pages.pages')),
                ('tagsid', models.ForeignKey(blank=True, db_column='TagsID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Tags.tags')),
            ],
            options={
                'db_table': 'tagsperpage',
            },
        ),
    ]
