# Generated by Django 4.0.2 on 2023-11-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TagsPerPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagsperpage',
            old_name='pageid',
            new_name='pageId',
        ),
        migrations.RenameField(
            model_name='tagsperpage',
            old_name='tagsid',
            new_name='tagsId',
        ),
        migrations.RenameField(
            model_name='tagsperpage',
            old_name='tagsperpageid',
            new_name='tagsperpageId',
        ),
    ]
