# Generated by Django 4.0.2 on 2024-11-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_tone', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('dark', 'Dark')], default='medium', max_length=10)),
                ('hair_color', models.CharField(choices=[('blonde', 'Blonde'), ('brown', 'Brown'), ('black', 'Black'), ('red', 'Red')], default='brown', max_length=10)),
                ('accessory', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
