# Generated by Django 4.0.2 on 2024-11-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
