# Generated by Django 4.0.2 on 2025-05-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPoints', '0002_userpoints_delete_userpointslog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpoints',
            table='userpoints',
        ),
    ]
