# Generated by Django 4.0.2 on 2025-04-09 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0003_alter_user_level'),
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookProgress',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'TODO'), (1, 'Completado'), (2, 'En progreso')], db_column='Status', default=0)),
                ('calificacion', models.FloatField(blank=True, db_column='Calificacion', null=True)),
                ('book', models.ForeignKey(db_column='BookId', on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
            options={
                'db_table': 'userbookprogress',
            },
        ),
    ]
