# Generated by Django 4.0.2 on 2022-10-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tagsId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
