# Generated by Django 4.0.2 on 2024-11-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tagsid', models.AutoField(db_column='TagsId', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=50, unique=True)),
                ('descriptionn', models.CharField(db_column='descriptionn', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
