# Generated by Django 4.0.2 on 2023-11-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='description',
            field=models.CharField(db_column='description', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='descriptionn',
            field=models.CharField(db_column='descriptionn', max_length=50, unique=True),
        ),
    ]
