# Generated by Django 4.0.2 on 2022-11-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
