# Generated by Django 4.0.2 on 2023-09-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Roles', '0002_alter_roles_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='roles',
            field=models.ManyToManyField(to='Roles.Roles'),
        ),
        migrations.AddField(
            model_name='userroles',
            name='user',
            field=models.ManyToManyField(to='Users.User'),
        ),
    ]
