# Generated by Django 4.0.2 on 2023-09-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0003_userroles_roles_userroles_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
