# Generated by Django 4.0.2 on 2025-04-09 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Badges', '0002_badge_progress_placeholder_badge_show_progress'),
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBadge',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('badge', models.ForeignKey(db_column='BadgeId', on_delete=django.db.models.deletion.CASCADE, to='Badges.badge')),
                ('book', models.ForeignKey(db_column='BookId', on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
            options={
                'db_table': 'bookbadge',
                'unique_together': {('book', 'badge')},
            },
        ),
    ]
