# Generated by Django 4.0.2 on 2025-04-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbadge', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookbadge',
            unique_together=set(),
        ),
    ]
