# Generated by Django 4.0.2 on 2023-09-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0004_remove_media_route'),
        ('GroupsCreate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupscreate',
            name='image',
        ),
        migrations.AddField(
            model_name='groupscreate',
            name='idimage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Media.media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupscreate',
            name='isactive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupscreate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
