# Generated by Django 4.0.2 on 2023-10-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsGroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsgroups',
            name='isactive',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
