# Generated by Django 4.0.2 on 2023-10-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('gradesid', models.AutoField(db_column='GradesID', primary_key=True, serialize=False)),
                ('progress', models.IntegerField(blank=True, db_column='Progress', null=True)),
                ('grade', models.FloatField(blank=True, db_column='Grade', null=True)),
                ('booksid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
    ]
