# Generated by Django 4.0.2 on 2022-11-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Grades', '0002_rename_booksid_grades_booksid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='iduser',
            field=models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, related_name='iduserModel', to='Users.user'),
        ),
    ]
