# Generated by Django 4.0.2 on 2024-11-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('is_teacher_badge', models.BooleanField(default=False)),
            ],
        ),
    ]
