# Generated by Django 5.1.1 on 2024-11-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='progress_placeholder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='show_progress',
            field=models.BooleanField(default=False),
        ),
    ]
