# Generated by Django 4.0.2 on 2025-05-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0002_badge_progress_placeholder_badge_show_progress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='badge',
            table='badges',
        ),
    ]
