# Generated by Django 4.0.2 on 2025-09-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0003_alter_badge_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='progress_placeholder',
        ),
        migrations.AddField(
            model_name='badge',
            name='goal_points',
            field=models.IntegerField(default=1, help_text='Meta numérica para obtener el badge (1-100000)'),
        ),
    ]
