# Generated by Django 4.0.2 on 2024-11-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Media', '0001_initial'),
        ('Widget', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('idoption', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=500)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('iscorrect', models.IntegerField(blank=True, null=True)),
                ('isactive', models.IntegerField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
                ('idimage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Media.media')),
                ('idwidgetitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Widget.widgetitem')),
            ],
            options={
                'db_table': 'options',
            },
        ),
    ]
