# Generated by Django 4.0.2 on 2024-11-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBadge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
