# Generated by Django 4.0.2 on 2024-10-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBadge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
