# Generated by Django 5.1.1 on 2024-11-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBadge', '0002_alter_userbadge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
