# Generated by Django 4.0.2 on 2025-05-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserBadge', '0002_userbadge_achieved_userbadge_progress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userbadge',
            table='userbadge',
        ),
    ]
