# Generated by Django 4.0.2 on 2024-11-25 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('UserPointsLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpointslog',
            name='user',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
        ),
    ]
