# Generated by Django 4.0.2 on 2022-03-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='TeacherId',
            new_name='id',
        ),
    ]
