# Generated by Django 4.0.2 on 2022-03-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0002_rename_teacherid_teachers_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='id',
            new_name='TeacherId',
        ),
    ]
