# Generated by Django 4.0.2 on 2022-10-20 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.AutoField(db_column='bookid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=200)),
                ('category', models.IntegerField(blank=True, db_column='category', null=True)),
                ('portrait', models.CharField(blank=True, db_column='portrait', max_length=200, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='createdat', null=True)),
                ('lastupdateat', models.DateTimeField(blank=True, db_column='lastupdateat', null=True)),
                ('state', models.IntegerField(db_column='state')),
                ('sharedbook', models.IntegerField(blank=True, db_column='sharedbook', null=True)),
                ('createdby', models.ForeignKey(db_column='createdby', on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to='Users.user')),
                ('updatedby', models.ForeignKey(db_column='updatedby', on_delete=django.db.models.deletion.CASCADE, related_name='updatedby', to='Users.user')),
            ],
        ),
    ]
