# Generated by Django 4.0.2 on 2024-09-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_column='Title', max_length=200, unique=True),
        ),
    ]
