# Generated by Django 4.0.2 on 2022-10-18 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('foldersId', models.AutoField(primary_key=True, serialize=False)),
                ('nameFolders', models.CharField(max_length=200, null=True)),
                ('createdBy', models.ForeignKey(db_column='createdBy', on_delete=django.db.models.deletion.CASCADE, related_name='createdBy', to='Users.user')),
            ],
        ),
    ]
