# Generated by Django 4.0.2 on 2022-11-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='nameFolders',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
