# Generated by Django 4.0.2 on 2022-11-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('classesId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('lastupdateAt', models.DateTimeField(blank=True, null=True)),
                ('teacherAssigned', models.ForeignKey(db_column='teacherAssigned', on_delete=django.db.models.deletion.CASCADE, related_name='teacherassigned1', to='Users.user')),
            ],
        ),
    ]
