# Generated by Django 4.0.2 on 2023-10-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0002_classes_finishdate_classes_groupscreateid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='isactive',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
