# Generated by Django 4.0.2 on 2022-11-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Books', '0001_initial'),
        ('Sharedbooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedbooks',
            name='idbook',
        ),
        migrations.RemoveField(
            model_name='sharedbooks',
            name='iduser',
        ),
        migrations.AddField(
            model_name='sharedbooks',
            name='bookId',
            field=models.ForeignKey(db_column='bookId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookIdModel', to='Books.book'),
        ),
        migrations.AddField(
            model_name='sharedbooks',
            name='userId',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userIdmodel', to='Users.user'),
        ),
    ]
