# Generated by Django 4.0.2 on 2022-11-30 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
        ('Sharedbooks', '0002_remove_sharedbooks_idbook_remove_sharedbooks_iduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedbooks',
            name='bookId',
            field=models.ForeignKey(db_column='bookId', on_delete=django.db.models.deletion.CASCADE, related_name='bookIdModel', to='Books.book'),
        ),
    ]
