# Generated by Django 4.0.2 on 2022-11-15 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorList',
            fields=[
                ('authorlistid', models.AutoField(primary_key=True, serialize=False)),
                ('bookId', models.ForeignKey(db_column='bookId', on_delete=django.db.models.deletion.CASCADE, related_name='idbookdb', to='Books.book')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='iduserdb', to='Users.user')),
            ],
        ),
    ]
