# Generated by Django 4.0.2 on 2022-11-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorList',
            fields=[
                ('authorlistid', models.AutoField(db_column='authorlistid', primary_key=True, serialize=False)),
                ('idbook', models.ForeignKey(db_column='idbook', on_delete=django.db.models.deletion.CASCADE, related_name='idbook', to='Books.book')),
                ('iduser', models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, related_name='iduser', to='Users.user')),
            ],
        ),
    ]
