# Generated by Django 4.0.2 on 2024-11-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorList',
            fields=[
                ('authorlistid', models.AutoField(db_column='AuthorListId', primary_key=True, serialize=False)),
                ('bookid', models.ForeignKey(blank=True, db_column='BookID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('userid', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
            options={
                'db_table': 'authorlist',
            },
        ),
    ]
