# Generated by Django 4.0.2 on 2024-11-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitled',
            fields=[
                ('idsubtitled', models.AutoField(primary_key=True, serialize=False)),
                ('transcription', models.JSONField()),
                ('translation', models.JSONField()),
                ('idmedia', models.ForeignKey(db_column='idmedia', on_delete=django.db.models.deletion.CASCADE, to='Media.media')),
            ],
            options={
                'db_table': 'subtitled',
            },
        ),
    ]
