# Generated by Django 4.0.2 on 2023-11-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0004_media_type'),
        ('Subtitled', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitled',
            name='idmedia',
            field=models.ForeignKey(db_column='idmedia', on_delete=django.db.models.deletion.CASCADE, to='Media.media'),
        ),
    ]
