# Generated by Django 4.0.2 on 2023-09-22 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classes', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesLog',
            fields=[
                ('classeslogid', models.AutoField(db_column='ClassesLogId', primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Description', max_length=100, null=True)),
                ('classesid', models.ForeignKey(db_column='ClassesID', on_delete=django.db.models.deletion.CASCADE, to='Classes.classes')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
            options={
                'db_table': 'classeslog',
            },
        ),
    ]
