# Generated by Django 4.1.3 on 2022-11-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classes', '0002_alter_classes_name'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesLog',
            fields=[
                ('classeslogid', models.AutoField(primary_key=True, serialize=False)),
                ('createat', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('classesid', models.ForeignKey(db_column='classesid', on_delete=django.db.models.deletion.CASCADE, related_name='classesid1', to='Classes.classes')),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='userId2', to='Users.user')),
            ],
        ),
    ]
