# Generated by Django 4.1.1 on 2022-10-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('widgetid', models.AutoField(db_column='widgetid', primary_key=True, serialize=False)),
                ('type', models.IntegerField(blank=True, db_column='type', null=True)),
                ('name', models.CharField(db_column='name', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetItem',
            fields=[
                ('widgetitemid', models.AutoField(db_column='widgetitemid', primary_key=True, serialize=False)),
                ('value', models.IntegerField(blank=True, db_column='value', null=True)),
                ('type', models.IntegerField(blank=True, db_column='type', null=True)),
                ('page', models.ForeignKey(db_column='page', on_delete=django.db.models.deletion.CASCADE, related_name='page', to='Pages.pages')),
                ('widget', models.ForeignKey(db_column='widget', on_delete=django.db.models.deletion.CASCADE, related_name='widget', to='Widget.widget')),
            ],
        ),
    ]
