# Generated by Django 4.0.2 on 2023-10-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Widget', '0002_alter_widgetitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetitem',
            name='value',
            field=models.CharField(blank=True, db_column='Value', max_length=1000, null=True),
        ),
    ]
