# Generated by Django 4.0.2 on 2023-11-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Widget', '0003_alter_widgetitem_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetitem',
            name='elementorder',
            field=models.IntegerField(blank=True, db_column='ElementOrder', null=True),
        ),
        migrations.AlterField(
            model_name='widgetitem',
            name='value',
            field=models.JSONField(blank=True, db_column='Value', null=True),
        ),
    ]
