# Generated by Django 4.0.2 on 2024-10-18 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Team', '0001_initial'),
        ('User_Levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('team', models.ForeignKey(db_column='TeamId', on_delete=django.db.models.deletion.CASCADE, to='Team.team')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='User_Levels.user')),
            ],
            options={
                'db_table': 'teamuser',
            },
        ),
    ]
