# Generated by Django 4.0.2 on 2022-10-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0001_initial'),
        ('Users', '0001_initial'),
        ('Tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('FileId', models.AutoField(primary_key=True, serialize=False)),
                ('fileLocation', models.URLField(null=True)),
                ('idFolders', models.ForeignKey(db_column='idFolders', on_delete=django.db.models.deletion.CASCADE, related_name='idFolders', to='folder.folder')),
                ('idTags', models.ForeignKey(db_column='idTags', on_delete=django.db.models.deletion.CASCADE, related_name='idTags', to='Tags.tags')),
                ('uploadBy', models.ForeignKey(db_column='uploadBy', on_delete=django.db.models.deletion.CASCADE, related_name='uploadBy', to='Users.user')),
            ],
        ),
    ]
