# Generated by Django 4.0.2 on 2022-10-26 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0001_initial'),
        ('Tags', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileid', models.AutoField(db_column='fileid', primary_key=True, serialize=False)),
                ('namefile', models.CharField(db_column='namefile', max_length=200, unique=True)),
                ('filelocation', models.FileField(upload_to='archivos/')),
                ('idfolder', models.ForeignKey(db_column='idfolder', on_delete=django.db.models.deletion.CASCADE, related_name='idfolder', to='folder.folder')),
                ('idtags', models.ForeignKey(db_column='idtags', on_delete=django.db.models.deletion.CASCADE, related_name='idtags', to='Tags.tags')),
                ('uploadby', models.ForeignKey(db_column='uploadby', on_delete=django.db.models.deletion.CASCADE, related_name='uploadby', to='Users.user')),
            ],
        ),
    ]
