# Generated by Django 4.0.2 on 2023-09-22 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0001_initial'),
        ('Tags', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileid', models.AutoField(db_column='FileId', primary_key=True, serialize=False)),
                ('filelocation', models.CharField(db_column='FileLocation', max_length=200)),
                ('foldersid', models.ForeignKey(db_column='FoldersId', on_delete=django.db.models.deletion.CASCADE, to='folder.folder')),
                ('idtags', models.ForeignKey(blank=True, db_column='IdTags', null=True, on_delete=django.db.models.deletion.CASCADE, to='Tags.tags')),
                ('uploadby', models.ForeignKey(db_column='UploadBy', on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
