# Generated by Django 4.0.2 on 2022-10-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filelocation',
            field=models.FileField(blank=True, default='', null=True, upload_to='archivos/'),
        ),
    ]
