# Generated by Django 4.0.2 on 2023-10-26 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='namefile',
            field=models.CharField(db_column='Namefile', default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
