# Generated by Django 4.0.2 on 2022-10-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='namefile',
            field=models.CharField(db_column='namefile', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='fileLocation',
            field=models.FileField(max_length=254, upload_to='archivos/'),
        ),
    ]
