# Generated by Django 4.0.2 on 2022-10-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0002_alter_file_filelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filelocation',
            field=models.FileField(blank=True, default='', max_length=10000, null=True, upload_to='archivos/'),
        ),
    ]
