# Generated by Django 4.0.2 on 2024-11-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classes', '0001_initial'),
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksPerClasses',
            fields=[
                ('booksperclasses', models.AutoField(db_column='BooksPerClasses', primary_key=True, serialize=False)),
                ('order', models.IntegerField(blank=True, db_column='Order', null=True)),
                ('isactive', models.IntegerField(blank=True, null=True)),
                ('booksid', models.ForeignKey(blank=True, db_column='BooksId', null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('classesid', models.ForeignKey(blank=True, db_column='ClassesId', null=True, on_delete=django.db.models.deletion.CASCADE, to='Classes.classes')),
            ],
            options={
                'db_table': 'booksperclasses',
            },
        ),
    ]
