# Generated by Django 4.0.2 on 2023-10-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksPerClasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksperclasses',
            name='order',
            field=models.IntegerField(blank=True, db_column='Order', null=True),
        ),
    ]
