# Generated by Django 4.0.2 on 2023-09-22 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tags', '0001_initial'),
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagsperbook',
            fields=[
                ('tagsperbookid', models.AutoField(db_column='TagsPerBookId', primary_key=True, serialize=False)),
                ('bookid', models.ForeignKey(blank=True, db_column='BookId', null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('tagsid', models.ForeignKey(blank=True, db_column='TagsID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Tags.tags')),
            ],
            options={
                'db_table': 'tagsperbook',
            },
        ),
    ]
